default: &default
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000

development:
    <<: *default
    database: simple_store_development

test:
    <<: *default
    database: simple_store_test

production:
    <<: *default
    database: simple_store__production
    username: simple_store_
    password: <%= ENV['SIMPLE_STORE_DATABASE_PASSWORD'] %>
